config/routes.rb
Rails.application.routes.draw do
  root 'conversations#index'

  get '/conversations/search', to: 'conversations_search#index'
  resources :conversations, except: [:destroy, :edit, :update] do
    resources :messages, only: [:create, :show] do
      resources :thoughts, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :thoughts, through: :messages, dependent: :destroy

  validates :title, :start_date, presence: true

  class << self
    def search(params)
      cleaned_query = "%#{params[:search]}%"
      Conversation.where("title LIKE ?", cleaned_query)
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  has_many :thoughts
  validates :text, presence: true
end

app/models/thought.rb
class Thought < ApplicationRecord
  belongs_to :message
  validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @conversations = Conversation.all
  end
  
  def show
    @conversation = Conversation.find(params[:id])
  end

  def new; end

  def create
    conversation = Conversation.create(title: params[:title], start_date: Date.today)
    if conversation.save
      flash[:success] = "Your Conversation Was Started!"
      redirect_to conversations_path
    else
      flash[:error] = "Whoops! Looks like you forgot a title!"
      render :new
    end
  end
end

app/controllers/conversations_search_controller.rb
class ConversationsSearchController < ApplicationController
  def index
    @results = Conversation.search(search_params)
  end

  private

  def search_params
    params.permit(:search)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    message = Message.create(text: params['text'], conversation_id: params['conversation_id'].to_i)
    if message.save
      flash[:success] = 'Message Added!'
    else
      flash[:error] = 'Message needs text!'
    end
    redirect_to conversation_path(params['conversation_id'].to_i)
  end

  def show
    conversation = Conversation.find(params[:conversation_id].to_i)
    @message = conversation.messages.find(params[:id].to_i)
  end
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  def create
    message = Message.find(params['message_id'])
    thought = Thought.create(text: params[:text], message: message)
    if thought.save
      flash[:success] = 'Comment Added!'
      redirect_to conversation_path(params['conversation_id'].to_i)
    else
      flash[:error] = 'Comment needs text!'
      redirect_to "/conversations/#{params['conversation_id']}/messages/#{params['message_id']}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/index.html.erb
<div>
  <div>
    <h2>All Conversations</h2>
  </div>
  <div class="search">
    <%= form_tag "/conversations/search", method: :get do %>
      <%= text_field_tag(:search, params[:search]) %>
      <%= submit_tag("Search") %>
    <% end %>
  </div>
  <div>
    <% if @conversations %>
      <ul>
        <% @conversations.each do |convo| %>
          <li><%= link_to "#{convo.title}",  conversation_path(convo.id)%> <%= convo.start_date %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div>
    <h3><%= link_to "Start New Conversation", new_conversation_path %></h3>
  </div>
</div>

app/views/conversations/new.html.erb
<div>
  <h1>Start a New Conversation</h1>
  <div>
    <%= form_tag(conversations_path, method: :post) do %>
      <%= label_tag :title %>
      <%= text_field_tag :title %>
      <%= button_tag 'Create Conversation' %>
    <% end %>
  </div>
</div>

app/views/conversations/show.html.erb
<div>
  <h1><%= @conversation.title %></h1>
  <div>
    <% @conversation.messages.each do |message| %>
      <div id="message-<%= message.id %>">
        <%= message.text %> - <%= message.created_at %>
        <ul>
          <% message.thoughts.each do |thought| %>
            <li>
              <p><%= thought.text %> - <%= thought.created_at %></p>
            </li>
          <% end %>
        </ul>
        <div>
          <%= link_to "Comment", "/conversations/#{@conversation.id}/messages/#{message.id}" %>
        </div>
      </div>
    <% end %>
  </div>
  <div>
    <h1>Join the conversation</h1>
    <%= form_tag("/conversations/#{@conversation.id}/messages", method: :post) do %>
      <%= label_tag :text %>
      <%= text_field_tag :text %>
      <%= button_tag 'Add Message' %>
    <% end %>
  </div>
</div>

app/views/conversations_search/index.html.erb
<div>
  <h1>Your Search Results</h1>
  <% unless @results.empty? %>
    <% @results.each do |convo| %>
      <div>
        <h3><%= link_to convo.title, conversation_path(convo.id) %></h3>
        <p><%= convo.start_date %></p>
      </div>
    <% end %>
  <% else %>
    <h3>No Conversations match your criteria, search again?</h3>
  <% end %>
  <div class="search">
    <h2>Search Again</h2>
    <%= form_tag "/conversations/search", method: :get do %>
      <%= text_field_tag(:search, params[:search]) %>
      <%= submit_tag("Search") %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RemeshProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <div>
        <h3><%= message %></h3>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/messages/show.html.erb
<div>
  <div>
    <h1>Conversation: <%= @message.conversation.title %></h1>
  </div>
  <div>
    <h3>Message Thread</h3>
    <p><%= @message.text %></p>
  </div>
  <div>
    <ul>
      <% @message.thoughts.each do |thought| %>
        <li><%= thought.text %> - <%= thought.created_at %> </li>
      <% end %>
    </ul>
    <%= 
      form_tag(
        "/conversations/#{@message.conversation.id}/messages/#{@message.id}/thoughts", 
        method: :post
        ) do 
    %>
      <%= label_tag :text %>
      <%= text_field_tag :text %>
      <%= button_tag 'Add Thought' %>
    <% end %>
  </div>
</div>